Add initial orb config.

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -22,19 +22,42 @@ release-filters: &release-filters
 jobs:
   # Create jobs to test the commands of your orbs.
   # You may want to add additional validation steps to ensure the commands are working as expected.
-  command-test:
+
+  test-authenticate_with_oidc:
     docker:
       - image: cimg/base:current
+    resource_class: small
     steps:
       - checkout
-      # Run your orb's commands to validate them.
-      - cloudsmith-oidc/greet
+      - cloudsmith-oidc/authenticate_with_oidc:
+          service_account: "circleci-orb-testing"
+      - run:
+          name: Assert environment variables have been set
+          command: | 
+            if [ $CLOUDSMITH_ORGANISATION != "financial-times" ]
+            then
+              echo "Test failed: CLOUDSMITH_ORGANISATION has not been set correctly."
+              exit 1
+            fi
+            if [ $CLOUDSMITH_SERVICE_ACCOUNT != "circleci-orb-testing" ]
+            then
+              echo "Test failed: CLOUDSMITH_SERVICE_ACCOUNT has not been set."
+              exit 1
+            fi
+            if [ -z $CLOUDSMITH_OIDC_TOKEN ]
+            then
+              echo "Test failed: CLOUDSMITH_OIDC_TOKEN has not been set."
+              exit 1
+            fi
+            echo "All tests passed."
+
 workflows:
   test-deploy:
     jobs:
       # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
       # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
-      - command-test:
+      - test-authenticate_with_oidc:
+          context: circleci-orb-publishing
           filters: *filters
       # The orb must be re-packed for publishing, and saved to the workspace.
       - orb-tools/pack:
@@ -46,6 +69,7 @@ workflows:
           # Ensure this job requires all test jobs and the pack job.
           requires:
             - orb-tools/pack
-            - command-test
-          context: orb-publishing
+            - test-authenticate_with_oidc
+          # Use a context to hold your publishing token.
+          context: circleci-orb-publishing
           filters: *release-filters
